name: "ilo"
version: "1.0"
config-version: 2

profile: clickhouse_ftw

model-paths: ["models"]
macro-paths: ["macros"]

models:
  ilo:

    clean:
      +schema: clean_grp6
      +materialized: table

    mart:
      +schema: mart_grp6
      +materialized: view
