clickhouse_ftw:
  target: remote
  outputs:
    remote:
      type: clickhouse
      host: 54.87.106.52
      port: 8123
      user: ftw_grp6
      password: Mewtwo!150#FTW
      
      schema: raw_grp6

      threads: 4
      secure: false
