name: 'lfs_data'
version: '1.0'
config-version: 2

profile: 'lfs_data'

model-paths: ["models"]

models:
  lfs_data:
    clean:
      +schema: clean_grp6
      +materialized: table
    mart:
      +schema: mart_grp6
      +materialized: view
